### PR TITLE
Fix multiple presenters bug

### LINKED ISSUE #91: RuntimeException with 2 or more presenters
If there are two or more presenters and the view is destroyed, when the getView () method is invoked the proxy works for a presenter but not for more.
If two or more are implemented, only the last one works.

Example:
```
_public class CharacterDetailsActivity extends MarvelActivity
    implements **CharacterCrashDetailsPresenter.View**, CharacterDetailsPresenter.View {...}_

Process: com.karumi.rosie.sample, PID: 20529
                                                   java.lang.RuntimeException: Internal error invoking the success object
                                                       at com.karumi.rosie.domain.usecase.RosieUseCase$1.run(RosieUseCase.java:114)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:234)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5526)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.karumi.rosie.domain.usecase.RosieUseCase$1.run(RosieUseCase.java:112)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:234)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5526)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                    Caused by: java.lang.ClassCastException: $Proxy5 cannot be cast to com.karumi.rosie.sample.characters.view.presenter.CharacterCrashDetailsPresenter$View
                                                       at com.karumi.rosie.sample.characters.view.presenter.CharacterCrashDetailsPresenter$2.onCharacterDetailsLoaded(CharacterCrashDetailsPresenter.java:62)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.karumi.rosie.domain.usecase.RosieUseCase$1.run(RosieUseCase.java:112)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:234)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5526)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```
Thanks in advance.

### PR DESCRIPTION
**Pull request by pedrovgs**
### :pushpin: References
* **Issue:** Fixes #91 

### :tophat: What is the goal?

Fix the bug reported by @jguerrero-icinetic. Reading the user report and the trace I thought the crash was related to the number of presenters, but after researching and trying to reproduce the bug by myself I noticed that the issue was related to the numbers of interfaces. Before this fix, if the Activity using a presenter implements more than one interface ``RosiePresenter.View`` just one interface was being used when replacing the view instance with the empty handler proxy. This generates a crash because the proxy generated did not implement the expected methods.

This PR updates the presenter implementation without any breaking change changing how the view proxy is generated implementing every interface extending from ``RosiePresenter.View`` instead of just one. 

I've also noticed that for some reason Travis started failing during the emulator startup so I decided to remove the execution of the instrumentation tests from the CI build. Sorry for the inconveniences, but Travis is not working right now and I'd like to publish a new release with this fix.

### How can it be tested?

Automatically 🤖

### CODE REVIEW

File: rosie/src/main/java/com/karumi/rosie/view/RosieViewProxyGenerator.java [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+    ClassLoader classLoader = viewClasses[0].getClassLoader();
+    return (T) Proxy.newProxyInstance(classLoader, viewClasses, EMPTY_HANDLER);
+  }
+
+  private Class<?>[] getViewInterfaceClasses(Object view) {
+    List<Class<?>> interfaceClasses = new LinkedList<>();
+    Class<?>[] interfaces = view.getClass().getInterfaces();
+    for (int i = 0; i < interfaces.length; i++) {
+      Class<?> interfaceCandidate = interfaces[i];
+      if (RosiePresenter.View.class.isAssignableFrom(interfaceCandidate)) {
```
Comment (flipper83) [inline rosie/src/main/java/com/karumi/rosie/view/RosieViewProxyGenerator.java]: this is good catched

**Comment by pedrovgs** [comment]
Thanks for the review @flipper83

**Comment by jguerrero-icinetic** [comment]
Works perfectly, good job !!! 👌👌👌 Thanks @pedrovgs & @flipper83 !!!
